# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# my additions
format = """
$directory\
$rust\
$fill\
$git_status\
$git_branch\
$time\
$battery\
$line_break\
$character
"""
add_newline = false
command_timeout = 9999

[fill]
symbol = " "

[directory]
style = "blue"
read_only = " ï ½"
truncation_length = 9999
truncate_to_repo = false

[git_branch]
symbol = "ï˜ "
format = "[$symbol$branch]($style) "
style = "bright-black"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[rust]
format = '[$symbol($version )]($style)'
symbol = 'ğŸ¦€ '
version_format = ''

[time]
disabled = false
style = "blue"
format = "[$time]($style)"

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vicmd_symbol = "[â®](bold purple)"
